config:
  cfg_files:
    actions: cf_actions.yaml
    aliases: cf_aliases.yaml
    highlight: cf_highlight.yaml
  rcv_text:
    auto_scroll: true
    hex: false
    max_rows: 5000
  rect:
    height: 667
    width: 1280
    x: 0
    y: 23
  snd_text:
    carrier_return: true
    hex: false
    line_feed: true
  uart:
    baud: 115200
    data: 8
    name: ''
    parity: N
    stop: 1.0
