config:
  auto_scroll: true
  hex:
    received: false
    sent: false
  max_rows: 2000
  rect:
    height: 667
    width: 1280
    x: 0
    y: 23
  uart:
    baud: 115200
    data: 8
    name: COM3
    parity: N
    stop: 1.0
