config:
  rcv_text:
    hex: false
    max_rows: 2000
    auto_scroll: true
  snd_text:
    hex: false
    carrier_return: false
    line_feed: false
  rect:
    height: 667
    width: 1280
    x: 0
    y: 23
  uart:
    baud: 115200
    data: 8
    name: COM3
    parity: N
    stop: 1.0
