config:
  cfg_files:
    aliases: aliases.yaml
    highlight: highlight.yaml
  rcv_text:
    auto_scroll: false
    hex: false
    max_rows: 20000
  rect:
    height: 667
    width: 1280
    x: 0
    y: 23
  snd_text:
    carrier_return: true
    hex: false
    line_feed: true
  uart:
    baud: 115200
    data: 8
    name: COM3
    parity: N
    stop: 1.0
